name: video_chat
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animator: ^2.0.1
  auto_direction: ^0.0.4+1
  cached_network_image: ^2.3.3
  camera: ^0.5.8+11
  cloud_firestore: ^0.13.4
  cupertino_icons: ^1.0.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.0.6
  flutter_image_compress: ^0.7.0
  firebase_database:
  google_sign_in: ^4.1.1

  http: ^0.12.2
  image_cropper: ^1.3.1
  image_downloader: ^0.20.1
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  ionicons: ^0.0.3
  liquid_swipe: ^1.5.0
  location: ^3.0.2
  path_provider: ^1.6.22
  provider: ^4.3.2+2
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  timeago: ^2.0.28
  url_launcher: ^5.7.10
  eva_icons_flutter: 2.0.1
  uuid: ^2.2.2
  lottie: ^0.6.0


  path:
  flutter_launcher_icons: 0.7.5
  sliding_up_panel: ^1.0.2
  fluttertoast: ^5.0.1
  permission_handler: ^3.0.0
  font_awesome_flutter: 8.8.1
  random_color: ^1.0.5
  date_format: ^1.0.8
  flutter_local_notifications:
  story: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/images/user_placeholder.jpg
    # - assets/images/video_chat_logo.png
    # - assets/images/shutter.png
    # - assets/images/switch_camera.png
    # - assets/images/gallery_button.png
    # - assets/images/verfiriedUserBadge.png
 
